apiVersion: batch/v1
kind: Job
metadata:
  name: sei-inicializador
  namespace: sei-prodesp
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sei-inicializador
    spec:
      containers:
      - command:
        - /entrypoint-atualizador.sh
        envFrom:
        - configMapRef:
            name: sei-app
        - secretRef:
            name: sei-secret1
        image: processoeletronico/app-ci:latest
        imagePullPolicy: Always
        name: sei-inicializador
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt
          name: vol1
        - mountPath: /sei/arquivos_externos_sei/
          name: vol2
        - mountPath: /sei/controlador-instalacoes
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: vol-sei-fontes
      - name: vol2
        persistentVolumeClaim:
          claimName: vol-sei-arquivosexternos
      - name: vol3
        persistentVolumeClaim:
          claimName: vol-sei-controladorinstalacao


