apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-arquivosexternos
  namespace: sei-prodesp
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-controladorinstalacao
  namespace: sei-prodesp
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

---
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-db
  namespace: sei-prodesp
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-fontes
  namespace: sei-prodesp
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-solr
  namespace: sei-prodesp
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
